name: Prevent Direct Pushes and Trigger Terraform

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enforce branch protection
        run: |
          if [[ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]]; then
            echo "Direct pushes to main are not allowed. Please use a pull request."
            exit 1
          fi

on:
  pull_request:
    branches:
      - main

jobs:
  run-terraform-on-pull-request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_api_key: ${{ secrets.TF_API_TOKEN }}
