name: Enforce Branch Protection

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enforce branch protection
        run: |
          protected_branches="main"
          current_branch=$(git rev-parse --abbrev-ref HEAD)

          for branch in $protected_branches
          do
            if [[ "$current_branch" == "$branch" ]]; then
              echo "Pushes directly to $branch are not allowed. Please create a pull request."
              exit 1
            fi
          done
