name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Prevent direct pushes to main
      - name: Check if push to main
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ] && [ "${{ github.event_name }}" == "push" ]; then
            echo "Direct push to main is not allowed"
            exit 1
          fi

      # Trigger Terraform run on merge
      - name: Trigger Terraform Run
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: |
          # Replace with your Terraform Cloud API token and organization
          TF_API_TOKEN=secrets.TF_API_TOKEN
          TF_ORG=KuTest

          # Install terraform-cli
          npm install -g terraform-cli-args

          # Trigger Terraform run
          terraform workspace select test-gt-actions
          terraform apply -auto-approve
