name: Enforce Branch Protection and Deploy to Terraform

# Trigger the workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enforce branch protection
        run: |
          protected_branch="main"
          current_branch=$(git rev-parse --abbrev-ref HEAD)

          if [[ "$current_branch" != "$protected_branch" ]]; then
            echo "Pushes directly to $protected_branch are not allowed. Please create a pull request."
            exit 1
          fi

  deploy-terraform:
    needs: enforce-branch-protection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}